spring.application.name=filemanager

app.filemanager.base-directory=storage

spring.security.user.name=admin
spring.security.user.password=admin
spring.security.user.role=ADMIN

springdoc.swagger-ui.enabled=true

spring.datasource.url=jdbc:postgresql://pg-29a3f253-haren-0320.i.aivencloud.com:24481/filemanager
spring.datasource.username=*****
spring.datasource.password=****

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true